version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: ec2-35-172-73-125.compute-1.amazonaws.com
            database: d7mheebspkejsg
            user: ibznwoatfqlgxz
            password: 7b0e6a50a39c68f681eed6feb98509679b1d34bc9fe9d3cbf267bc94cd35f7ed
            ssl: true
            rawAccess: true
            port: '5432'
            migrations: true